#!/bin/bash  
pd=$(pwd) 
for f in $(ls -F |grep "/$") 
  do 
 
      echo "$(cd $f )...........................${f}......................." 
      echo "$(git pull)" 
      echo "$(git add * && git commit -a -m 'publish' )" 
      echo "$(git push)" 
      echo "$(gitbook build . ${pd})..........build完成${pd}.............."
      cd ${pd} 
      echo "$(git add $f && git commit -a -m 'publish' )" 
      echo "$(git push)"  
       
       
  done 
 
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
~                                                                                                                                                                                                                                                                                         
 VISUAL  release.sh                                                                                                                                                                                                               sh  utf-8[unix]    5% ☰    1/18 ㏑ :  1  ☲ [14]trailing 
-- 可视 --

